package com.airdeck.hid;

public final class HidConnectionPolicyTest {
    private static int assertions;
    private static void equal(Object expected, Object actual, String label) {
        assertions++;
        if (expected == null ? actual != null : !expected.equals(actual))
            throw new AssertionError(label + ": expected=" + expected + ", actual=" + actual);
    }
    private static void check(boolean condition, String label) {
        assertions++;
        if (!condition) throw new AssertionError(label);
    }
    public static void main(String[] args) {
        ReconnectPolicy policy = new ReconnectPolicy("saved");
        equal("saved", policy.target(), "restore saved host");
        long[] delays = {600L, 2000L, 5000L, 10000L};
        for (int i = 0; i < delays.length; i++) {
            equal(delays[i], policy.reserveDelay(), "bounded backoff through short successful connections");
            long now = i * 2000L;
            check(policy.selectIncoming("saved"), "same target CONNECTING accepted");
            check(policy.selectIncoming("saved"), "duplicate CONNECTING accepted without renewing budget");
            policy.connected("saved", now);
            policy.connected("saved", now + 100);
            equal(i + 1, policy.attempts(), "CONNECTED and duplicates preserve attempt count");
            policy.disconnected("saved", now + 1000);
            policy.retryAvailable();
            equal(i + 1, policy.attempts(), "short disconnect and availability do not renew budget");
        }
        equal(-1L, policy.reserveDelay(), "four short connections exhaust retry budget");
        policy.retryAvailable();
        equal(-1L, policy.reserveDelay(), "foreground or Bluetooth return cannot revive exhausted loop");

        policy.connected("saved", 10000);
        policy.connected("saved", 20000);
        policy.disconnected("other", 90000);
        equal(4, policy.attempts(), "unrelated disconnect cannot reset active target budget");
        policy.disconnected("saved", 40000);
        equal(0, policy.attempts(), "30-second connection resets budget despite duplicate CONNECTED");
        equal(600L, policy.reserveDelay(), "stable connection restores first retry");
        policy.connected("saved", 50000);
        policy.disconnected("saved", 79999);
        equal(1, policy.attempts(), "29999 milliseconds is not stable");
        policy.disconnected("saved", 90000);
        equal(1, policy.attempts(), "late duplicate disconnect cannot retroactively grant stability");
        policy.connected("saved", 100000);
        policy.disconnected("saved", 99999);
        equal(1, policy.attempts(), "backward timestamp cannot grant stability");

        policy.select("new");
        equal("new", policy.target(), "manual target takes priority");
        equal(600L, policy.reserveDelay(), "manual target gets new retry budget");
        for (int i = 0; i < 5; i++) policy.reserveDelay();
        equal("new", policy.target(), "failed explicit connection never falls back to old device");
        check(!policy.accepts("saved"), "late old-host connection cannot override manual selection");
        check(!policy.selectIncoming("saved"), "incoming host cannot steal explicit in-flight selection");
        policy.connected("saved", 200000);
        equal("new", policy.target(), "rejected CONNECTED cannot change selected target");
        check(policy.accepts("new"), "selected device may finish connecting");
        check(policy.selectIncoming("new"), "same selected incoming callback accepted");
        equal(-1L, policy.reserveDelay(), "same incoming callback cannot renew exhausted budget");
        policy.connected("new", 210000);
        equal(4, policy.attempts(), "successful selected host keeps its budget until stable");
        check(policy.accepts("different"), "successful connection clears temporary explicit lock");
        policy.disconnected("new", 211000);
        check(policy.selectIncoming("different"), "new incoming host can replace remembered host");
        equal(0, policy.attempts(), "different target has its own retry budget");
        policy.reserveDelay();
        policy.connected("different", 220000);
        policy.disconnected("new", 300000);
        equal(1, policy.attempts(), "old target disconnect cannot reset new target budget");
        policy.newSession();
        equal("different", policy.target(), "new session remembers latest success");
        equal(600L, policy.reserveDelay(), "new app session explicitly restores budget");

        policy = new ReconnectPolicy("saved");
        policy.connected("saved", 0);
        policy.select("new");
        policy.reserveDelay();
        policy.disconnected("saved", 30000);
        equal(1, policy.attempts(), "stable old link cannot renew already-selected new target budget");

        policy = new ReconnectPolicy("saved");
        policy.reserveDelay();
        policy.connected("saved", 0);
        policy.beginPairing();
        check(policy.isPairing(), "pairing wait is explicit");
        equal(null, policy.target(), "pairing pauses old automatic target");
        equal(-1L, policy.reserveDelay(), "pairing does not reconnect remembered host");
        check(!policy.accepts("saved"), "late old connection cannot end pairing wait");
        check(!policy.selectIncoming("saved"), "old incoming completion rejected during pairing");
        policy.connected("saved", 100);
        check(policy.isPairing(), "rejected old success cannot end pairing wait");
        policy.retryAvailable();
        equal(1, policy.attempts(), "pairing availability does not renew old budget");
        check(policy.selectIncoming("new"), "new incoming selected while waiting");
        check(!policy.isPairing(), "incoming selection ends pairing wait");
        equal("new", policy.target(), "incoming host becomes current target");
        equal(0, policy.attempts(), "new paired host gets new budget");
        policy.connected("new", 1000);
        check(policy.accepts("next"), "saved host does not permanently lock incoming connections");
        policy.select("pending");
        policy.beginPairing();
        check(!policy.accepts("pending"), "pairing ignores abandoned explicit target");
        check(!policy.accepts("new"), "pairing ignores previous still-active host");
        check(policy.accepts("next"), "pairing allows another incoming host");
        policy.select("new");
        check(!policy.isPairing(), "explicit choice can select even the old pairing target");
        check(policy.accepts("new"), "explicit selection overrides pairing exclusion");

        policy.disconnect();
        equal(null, policy.target(), "manual disconnect prevents reconnect");
        check(!policy.accepts("new"), "late connection after deliberate disconnect is rejected");
        check(!policy.selectIncoming("different"), "incoming host cannot override manual stop");
        policy.retryAvailable();
        equal(-1L, policy.reserveDelay(), "foreground or Bluetooth return preserves manual stop");
        policy.beginPairing();
        check(policy.accepts("different"), "explicit pairing action resumes incoming acceptance");
        policy.select("new");
        equal("new", policy.target(), "manual connect resumes");
        policy.connected("new", 0);
        policy.newSession();
        equal("new", policy.target(), "new app session uses latest successful host");
        policy.select("unpaired");
        policy.forget("unpaired");
        equal(null, policy.target(), "unpairing explicit target cannot reconnect to old host");
        check(!policy.isSuppressed(), "forgetting explicit target does not globally suppress incoming hosts");
        check(!policy.accepts("unpaired"), "forgotten explicit target's late completion rejected");
        check(policy.accepts("different"), "different incoming host allowed after explicit target forgotten");
        policy.newSession();
        equal("new", policy.target(), "old successful host remains until replaced by success");
        policy.forget("new");
        equal(null, policy.target(), "unpaired remembered device removed");
        check(!policy.accepts("new"), "late connection cannot remember an unpaired host again");
        check(policy.accepts("different"), "forgetting remembered host does not ban another incoming host");
        equal(-1L, policy.reserveDelay(), "cannot retry without a remembered device");
        policy.beginPairing();
        check(policy.selectIncoming("different"), "unpair then pair a new device does not stay suppressed");
        policy = new ReconnectPolicy("saved");
        policy.select("new");
        policy.reserveDelay();
        policy.forget("unrelated");
        equal(1, policy.attempts(), "unpairing unrelated device preserves retry budget");
        policy.forget("saved");
        equal("new", policy.target(), "unpairing old host does not suppress selected new host");
        equal(1, policy.attempts(), "unpairing old host preserves selected target's budget");
        check(!policy.selectIncoming(null), "null incoming target ignored");
        check(!policy.selectIncoming(""), "empty incoming target ignored");

        policy = new ReconnectPolicy("saved");
        policy.connected("saved", 0);
        policy.beginPairing();
        policy.forget("saved");
        check(policy.isPairing(), "forgetting old host preserves pairing wait");
        check(!policy.isSuppressed(), "forgetting during pairing does not introduce manual suppression");
        check(policy.accepts("saved"), "explicit pairing permits same host after forgetting and re-pairing");
        check(policy.selectIncoming("new"), "forget old host during pairing still permits new host");
        policy.connected("new", 100);
        equal("new", policy.target(), "new incoming after forgetting becomes retry target");
        policy.forget("saved");
        check(!policy.accepts("saved"), "forgotten host remains excluded after new success");
        policy.select("saved");
        check(policy.accepts("saved"), "explicit selection clears that forgotten address restriction");
        policy.forget("saved");
        check(!policy.accepts("saved"), "new forget excludes it again");
        policy.beginPairing();
        check(policy.accepts("saved"), "new pairing action permits re-pairing a forgotten address");
        policy.disconnect();
        policy.forget("new");
        check(!policy.accepts("different"), "forgetting cannot undo a deliberate manual stop");

        policy = new ReconnectPolicy("saved");
        policy.beginPairing();
        policy.forget("saved");
        check(policy.selectIncoming("saved"), "same pairing session can reclaim a re-paired old address");
        policy.connected("saved", 1000);
        equal("saved", policy.target(), "re-paired host is remembered after successful connection");
        check(!policy.isPairing(), "successful re-pair exits pairing wait");

        HidProtocolDiagnostics diagnostic = new HidProtocolDiagnostics();
        equal(null, diagnostic.warning(), "unknown host cache is not an error");
        for (int id = 1; id <= 3; id++) diagnostic.getReport(1, id);
        diagnostic.getReport(2, 1);
        diagnostic.getReport(3, 0);
        diagnostic.output(2, 1, 1);
        diagnostic.output(3, 0, 0);
        equal(null, diagnostic.warning(), "valid reports, LED feedback and feature probes are normal");
        diagnostic.protocol(0);
        check(diagnostic.warning().contains("手柄和鼠标滚轮不可用"), "boot mode explicitly warns about limitations");
        diagnostic.getReport(1, 1);
        diagnostic.getReport(1, 2);
        diagnostic.output(2, 1, 1);
        check(!diagnostic.warning().contains("缓存"), "boot reports must not claim a stale cache");
        diagnostic.protocol(1);
        equal(null, diagnostic.warning(), "return to report protocol clears boot-only warning");
        diagnostic.getReport(2, 2);
        check(diagnostic.warning().contains("类型 2，编号 2"), "old swapped keyboard report ID detected");
        check(diagnostic.warning().contains("可能"), "host cache mismatch is a possibility, not proof");
        diagnostic.output(2, 1, 1);
        check(diagnostic.warning() != null, "one good LED packet cannot hide earlier incompatibility");
        diagnostic.reset();
        equal(null, diagnostic.warning(), "new connection clears stale evidence");
        diagnostic.output(2, 1, 8);
        check(diagnostic.warning().contains("长度 8"), "invalid output length detected");
        diagnostic.reset();
        diagnostic.output(2, 1, -1);
        check(diagnostic.warning() != null, "null output rejected");
        diagnostic.reset();
        diagnostic.protocol(255);
        check(diagnostic.warning().contains("未知协议模式"), "unknown mode detected");
        diagnostic.reset();
        diagnostic.getReport(0, 1);
        check(diagnostic.warning() != null, "invalid report type detected");
        System.out.println("PASS: " + assertions + " connection/diagnostic assertions");
    }
}
